language: ruby
rvm:
  - 2.2

install: 
  - gem install jekyll -v 3.3.1 
  - gem install jekyll-redirect-from jekyll-paginate jekyll-minify-html jekyll-seo-tag jekyll-sitemap
  - gem install s3_website
  - gem install html-proofer

script: 
  - jekyll build
  - htmlproof _site

after_success: s3_website push
