# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Plugins
gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-minify-html
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalinks
permalink:        pretty

# Setup
title:            Jaaga Coworking
tagline:          'Share office space and skills with startups and freelancers'
description:      'Cowork, Collaborate, Grow'
url:              https://jaagastartup.in
baseurl:          

author:
  name:           'Jaaga Coworking Community'
  url:            https://www.facebook.com/JaagaStartup
  email:          hello@jaagastartup.in

# paginate:         5
# paginate_path:    "/blog/page:num/"

# Custom vars
version:          0.1

exclude:
  - node_modules
  - Gulpfile.js
  - package.json
  - build+deploy.sh
  - s3_website.yml
  - README.md