- menu_name: "Services"

- name: "Coworking"
  url: "/cowork/"
  title: "Coworking"

- name: "Events"
  url: "/events/"
  title: "Events"

- name: "Sustain"
  url: "/sustain/"
  title: "Sustain"

- name: "Jobs"
  url: "http://jobs.jaagastartup.in"
  title: "Jobs at our startups"

- name: "Terms and Conditions"
  url: "/terms/"
  title: "Terms and Conditions"
